apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-dev
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/techdocs-ref: url:https://${{values.git_host}}/${{values.gitlabGroup}}/${{values.repoName}}
    backstage.io/source-location: url:https://${{values.git_host}}/${{values.gitlabGroup}}/${{values.repoName}}
    janus-idp.io/tekton-enabled: 'true'
    gitlab.com/project-slug: ${{values.gitlabGroup}}/${{values.repoName}}
  tags:
    - blockchain
    - hyperledger-fabric
    - operator
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://${{values.git_host}}/${{values.gitlabGroup}}/${{values.repoName}}?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: workshop-system-${{values.namespace}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-${{values.namespace}}
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: ${{values.owner | dump}}
